# Docker Compose configuration for Campfire Emergency Helper

services:
  campfire:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campfire-emergency-helper
    ports:
      - "8000:8000"
    env_file:
      - deployment.env  # Copy from deployment.env.template and customize
    environment:
      # Override specific values here if needed
      CAMPFIRE_HOST: "0.0.0.0"
      CAMPFIRE_PORT: "8000"
    
    volumes:
      # Persistent data
      - campfire_data:/app/data
      - campfire_corpus:/app/corpus
      - campfire_logs:/app/logs
      
      # Optional: Mount custom policy
      # - ./custom-policy.md:/app/policy.md:ro
      
      # Optional: Mount raw documents for ingestion
      # - ./documents:/app/corpus/raw:ro
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    
    # Security
    security_opt:
      - no-new-privileges:true
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Ollama service for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: campfire-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    
    # GPU support (uncomment if you have NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    
    # Pull required model on startup
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama2:7b &&
        wait
      "

volumes:
  campfire_data:
    driver: local
  campfire_corpus:
    driver: local
  campfire_logs:
    driver: local
  ollama_data:
    driver: local

networks:
  default:
    name: campfire-network