[tool.uv]
# Configure uv for the campfire project
python = "3.11"

# Extra index URLs for specialized packages
extra-index-url = [
    "https://download.pytorch.org/whl/cpu",  # PyTorch CPU builds
    "https://pypi.org/simple/",              # Standard PyPI
]

# Development dependencies
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.7.0",
    "pre-commit>=3.5.0",
]

# Optional dependency groups
[tool.uv.sources]
# Configure sources for gpt-oss and related packages
# This will be updated once we have the specific wheel URLs

[tool.uv.pip]
# Pip-specific configuration
index-strategy = "unsafe-best-match"
keyring-provider = "disabled"